In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re
import html

In [18]:
countries = [
    "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia",
    "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
    "Hungary", "Iceland", "Ireland", "Italy", "Latvia", "Lithuania",
    "Luxembourg", "Netherlands", "Norway", "Malta", "Poland", "Portugal", "Romania",
    "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "United Kingdom"
]

In [19]:
links = []

for country in countries:
    country_no_space = country.replace(" ", "").lower()
    links.append(f"http://www.parties-and-elections.eu/{country_no_space}.html")


links

['http://www.parties-and-elections.eu/austria.html',
 'http://www.parties-and-elections.eu/belgium.html',
 'http://www.parties-and-elections.eu/bulgaria.html',
 'http://www.parties-and-elections.eu/croatia.html',
 'http://www.parties-and-elections.eu/cyprus.html',
 'http://www.parties-and-elections.eu/czechia.html',
 'http://www.parties-and-elections.eu/denmark.html',
 'http://www.parties-and-elections.eu/estonia.html',
 'http://www.parties-and-elections.eu/finland.html',
 'http://www.parties-and-elections.eu/france.html',
 'http://www.parties-and-elections.eu/germany.html',
 'http://www.parties-and-elections.eu/greece.html',
 'http://www.parties-and-elections.eu/hungary.html',
 'http://www.parties-and-elections.eu/iceland.html',
 'http://www.parties-and-elections.eu/ireland.html',
 'http://www.parties-and-elections.eu/italy.html',
 'http://www.parties-and-elections.eu/latvia.html',
 'http://www.parties-and-elections.eu/lithuania.html',
 'http://www.parties-and-elections.eu/luxembourg.html',
 'http://www.parties-and-elections.eu/netherlands.html',
 'http://www.parties-and-elections.eu/norway.html',
 'http://www.parties-and-elections.eu/malta.html',
 'http://www.parties-and-elections.eu/poland.html',
 'http://www.parties-and-elections.eu/portugal.html',
 'http://www.parties-and-elections.eu/romania.html',
 'http://www.parties-and-elections.eu/slovakia.html',
 'http://www.parties-and-elections.eu/slovenia.html',
 'http://www.parties-and-elections.eu/spain.html',
 'http://www.parties-and-elections.eu/sweden.html',
 'http://www.parties-and-elections.eu/switzerland.html',
 'http://www.parties-and-elections.eu/unitedkingdom.html']

In [22]:
trial_links = ['http://www.parties-and-elections.eu/bulgaria.html']

In [31]:
for url in trial_links:
    
    name = re.search(r'/([^/]+)\.html$', url).group(1)

    response = requests.get(url)

    response.encoding = 'windows-1252'

    soup = BeautifulSoup(response.text, "html.parser")

    tables = soup.find_all("table")

    
    tables = soup.find_all("table")
        
    target_table = tables[5]

    tables[5].get_text()

    rows = target_table.find_all("tr")

    table_values = []

    for row in rows:
        cells = row.find_all("td")
        values = [c.get_text(strip=True) for c in cells]
        table_values.append(values)
    
    print(table_values)
    
    header_call_number = len(table_values[1]) + 1

    party_information_raw = []

    for value in table_values:
        if len(value) == header_call_number: 
            party_information_raw.append(value)
        elif re.search(r'\(.*?\)', value[1]):
            party_information_raw.append(["", value[1]] + [""] * (header_call_number - 2))
    
    print(party_information_raw)

[['', '2026', '', '2024II', '', '2024I', '', '2023'], ['Party', 'Ideology', '%', 'Seats', '%', 'Seats', '%', 'Seats', '%', 'Seats'], ['', 'Graždani za Evropejsko Razvitie na Bălgaria (GERB)Citizens\r\n  for European Development of Bulgaria', 'Conservatism', '', '', '26,4', '65', '24,0', '66', '26,5', '67'], ['', 'Săjuz na Demokratični\r\n  Sili (SDS)Union\r\n  of Democratic Forces', 'ConservatismChristian democracy', '', '', '1', '2', '2'], ['', 'Prodŭlžavame Promjanata (PP)We\r\n  Continue the Change', 'Anti-corruption\r\n  politicsLiberalism', '', '', '14,2', '19', '13,9', '22', '24,5', '42'], ['', 'Demokratična Bălgaria (DB)Democratic\r\n  Bulgaria', 'LiberalismConservatism', '', '', '17', '17', '22'], ['', 'Văzraždane (V)Revival', 'National\r\n  conservatism', '', '', '13,4', '33', '13,4', '38', '14,2', '37'], ['', 'Dviženie za Prava i\r\n  Svobodi (DPS)Movement\r\n  for Rights and Freedoms', 'Minority\r\n  interests (TUR)Centrism', '', '', '11,5', '29', '16,6', '47', '13,7', '36'], ['', 'Bălgarska Socialističeska Partija (BSP)Bulgarian\r\n  Socialist Party (a)', 'Social democracy', '', '', '7,6', '19', '6,9', '19', '8,9', '23'], ['', 'Alians za Prava i Svobodi (APS)Alliance\r\n  for Rights and Freedoms', 'Minority\r\n  interests (TUR)Centrism', '', '', '7,5', '19', '-', '-', '-', '-'], ['', 'Ima Takav Narod (ITN)There\r\n  Is Such A People', 'Anti-corruption\r\n  politicsSocial conservatism', '', '', '6,8', '17', '5,8', '16', '4,1', '11'], ['', 'Moral, Edinstvo, Čest (MEČ)Morale,\r\n  Unity, Honour', 'Anti-corruption\r\n  politicsSocial conservatism', '', '', '4,6', '11', '2,9', '-', '-', '-'], ['', 'Velicie (VELICIE)Greatness', 'Anti-corruption\r\n  politicsEuroscepticism', '', '', '4,0', '10', '4,5', '13', '-', '-'], ['', 'Dviženie "Da, Bălgarija"\r\n  (DA)Movement\r\n  "Yes, Bulgaria"', 'Liberalism', '', '', 'DB', '(12)', 'DB', '(9)', 'DB', '(11)'], ['', 'Demokrati za Silna Bălgarija (DSB)Democrats\r\n  for a Strong Bulgaria', 'Conservatism', '', '', 'DB', '(5)', 'DB', '(8)', 'DB', '(8)'], ['', 'Zeleno Dviženie (ZD)Green\r\n  Movement', 'Green\r\n  politicsSocial liberalism', '', '', '-', '-', '0,4', '-', 'DB', '(3)'], ['Others', '', '', '4,0', '-', '11,6', '-', '10,3', '-'], ['Total', '', '', '-', '240', '-', '240', '-', '240'], ['Turnout', '', '38,9', '33,4', '40,6']]
[['', 'Graždani za Evropejsko Razvitie na Bălgaria (GERB)Citizens\r\n  for European Development of Bulgaria', 'Conservatism', '', '', '26,4', '65', '24,0', '66', '26,5', '67'], ['', 'Săjuz na Demokratični\r\n  Sili (SDS)Union\r\n  of Democratic Forces', '', '', '', '', '', '', '', '', ''], ['', 'Prodŭlžavame Promjanata (PP)We\r\n  Continue the Change', 'Anti-corruption\r\n  politicsLiberalism', '', '', '14,2', '19', '13,9', '22', '24,5', '42'], ['', 'Demokratična Bălgaria (DB)Democratic\r\n  Bulgaria', '', '', '', '', '', '', '', '', ''], ['', 'Văzraždane (V)Revival', 'National\r\n  conservatism', '', '', '13,4', '33', '13,4', '38', '14,2', '37'], ['', 'Dviženie za Prava i\r\n  Svobodi (DPS)Movement\r\n  for Rights and Freedoms', 'Minority\r\n  interests (TUR)Centrism', '', '', '11,5', '29', '16,6', '47', '13,7', '36'], ['', 'Bălgarska Socialističeska Partija (BSP)Bulgarian\r\n  Socialist Party (a)', 'Social democracy', '', '', '7,6', '19', '6,9', '19', '8,9', '23'], ['', 'Alians za Prava i Svobodi (APS)Alliance\r\n  for Rights and Freedoms', 'Minority\r\n  interests (TUR)Centrism', '', '', '7,5', '19', '-', '-', '-', '-'], ['', 'Ima Takav Narod (ITN)There\r\n  Is Such A People', 'Anti-corruption\r\n  politicsSocial conservatism', '', '', '6,8', '17', '5,8', '16', '4,1', '11'], ['', 'Moral, Edinstvo, Čest (MEČ)Morale,\r\n  Unity, Honour', 'Anti-corruption\r\n  politicsSocial conservatism', '', '', '4,6', '11', '2,9', '-', '-', '-'], ['', 'Velicie (VELICIE)Greatness', 'Anti-corruption\r\n  politicsEuroscepticism', '', '', '4,0', '10', '4,5', '13', '-', '-'], ['', 'Dviženie "Da, Bălgarija"\r\n  (DA)Movement\r\n  "Yes, Bulgaria"', 'Liberalism', '', '', 'DB', '(12)', 'DB', '(9)', 'DB', '(11)'], ['', 'Demokrati za Silna Bălgarija (DSB)Democrats\r\n  for a Strong Bulgaria', 'Conservatism', '', '', 'DB', '(5)', 'DB', '(8)', 'DB', '(8)'], ['', 'Zeleno Dviženie (ZD)Green\r\n  Movement', 'Green\r\n  politicsSocial liberalism', '', '', '-', '-', '0,4', '-', 'DB', '(3)']]

In [20]:
election_data = {}


for url in links:
    
    name = re.search(r'/([^/]+)\.html$', url).group(1)

    response = requests.get(url)

    response.encoding = 'windows-1252'

    soup = BeautifulSoup(response.text, "html.parser")

    tables = soup.find_all("table")

    try:
    
        tables = soup.find_all("table")
        
        target_table = tables[5]

        tables[5].get_text()

        rows = target_table.find_all("tr")

        table_values = []

        for row in rows:
            cells = row.find_all("td")
            values = [c.get_text(strip=True) for c in cells]
            table_values.append(values)
        
        header_call_number = len(table_values[1]) + 1

        party_information_raw = []

        for value in table_values:
            if len(value) == header_call_number: 
                party_information_raw.append(value)
            elif re.search(r'\(.*?\)', value[1]):
                party_information_raw.append(["", value[1]] + [""] * (header_call_number - 2))

        party_names = []
        election_results_all = []


        for value in party_information_raw: 
            party_names.append(value[1])
            election_results_all.append(value[3:])


        year_row = table_values[0]

        election_years = [v for v in year_row if re.search(r'\d+', v)]

        election_results_percent = []
        for result in election_results_all:
            election_results_percent.append(result[::2])

        cleaned_name = []
        name_short = []

        for party in party_names:
            clean = party.replace("\n", " ").replace("\r", " ").replace("\\", "").replace(" +", " ")

            clean = re.sub(r'\s+', ' ', clean)

            match = re.match(r'(.*?)\(', clean)
            
            if match:
                cleaned_name.append(match.group(1).strip())
            else:
                cleaned_name.append(clean.strip())
    
            within_parenthesis = re.search(r'\((.*?)\)', clean)

            if within_parenthesis:
                name_short.append(within_parenthesis.group(1).strip())
            else:
                name_short.append("")

        df = pd.concat([
            pd.Series(cleaned_name, name="Party"),
            pd.Series(name_short, name="Name_Short"),
            pd.DataFrame(election_results_percent, columns = election_years)
            ], axis = 1)

        election_data[name] = df
    
    except:
        print(name)

In [42]:
country_codes = {
    "austria": "AUT", "belgium": "BEL", "bulgaria": "BGR", "croatia": "HRV",
    "cyprus": "CYP", "czechia": "CZE", "denmark": "DNK", "estonia": "EST",
    "finland": "FIN", "france": "FRA", "germany": "DEU", "greece": "GRC",
    "hungary": "HUN", "iceland": "ISL", "ireland": "IRL", "italy": "ITA",
    "latvia": "LVA", "lithuania": "LTU", "luxembourg": "LUX", "malta": "MLT", "netherlands": "NLD",
    "norway": "NOR", "poland": "POL", "portugal": "PRT", "romania": "ROU",
    "slovakia": "SVK", "slovenia": "SVN", "spain": "ESP", "sweden": "SWE",
    "switzerland": "CHE", "unitedkingdom": "GBR"
}

for country_name, df in election_data.items():
    code = country_codes.get(country_name) 
    df["CountryCode"] = code

relevant_columns = ["Party", "Name_Short","2026", "2025", "2024", "2023", "2022", "CountryCode"]

for country_name, df in election_data.items():
    election_data[country_name] = df[[
        col for col in df.columns
        if any(term in col for term in relevant_columns)
    ]]

In [43]:
election_data["austria"]

                                        Party Name_Short  2024 CountryCode
0            freiheitliche partei osterreichs        fpo  28,8         AUT
1                 osterreichische volkspartei        ovp  26,3         AUT
2      sozialdemokratische partei osterreichs        spo  21,1         AUT
3     das neue osterreich und liberales forum       neos   9,1         AUT
4            die grunen die grune alternative      grune   8,2         AUT
5  kommunistische partei osterreichs kpo plus        kpo   2,4         AUT
6                            jetzt liste pilz      jetzt     -         AUT
7                team stronach fur osterreich         ts     -         AUT

In [ ]:
import string
import unicodedata

def remove_accents(text):
    if pd.isna(text):
        return text  # keep NaN as-is
    text = str(text)  # ensure it is a string
    return ''.join(c for c in unicodedata.normalize('NFKD', text) if not unicodedata.combining(c))

test_data = election_data.copy()

for k, v in test_data.items():
    v["Party"] = v["Party"].str.lower()
    v["Name_Short"] = v["Name_Short"].str.lower()
    # replace all non-letter characters with a space
    punctuation_regex = r'[!"\\#\$%\&\'\(\)\*\+,\-\./:;<=>\\?@\[\\\]\^_`\{\|\}\~\u2010-\u2015]'
    v["Party"] = v["Party"].str.replace(punctuation_regex, " ", regex=True)
    v["Name_Short"] = v["Name_Short"].str.replace(punctuation_regex, " ", regex=True)

    # replace multiple spaces with a single space and strip leading/trailing spaces
    v["Party"] = v["Party"].str.replace(r'\s+', ' ', regex=True).str.strip()
    v["Name_Short"] = v["Name_Short"].str.replace(r'\s+', ' ', regex=True).str.strip()

    
    v["Party"] = v["Party"].apply(remove_accents)
    v["Name_Short"] = v["Name_Short"].apply(remove_accents)



test_data["austria"]

'[!"\\\\#\\$%\\&\\\'\\(\\)\\*\\+,\\-\\./:;<=>\\\\?@\\[\\\\\\]\\^_`\\{\\|\\}\\~\\u2010-\\u2015]'

In [49]:
id_frame = pd.read_csv('/Users/lukefischer/Dropbox/The PopuList Repo/Data/populist_parlgov_id.csv')

id_frame = id_frame[id_frame["CountryCode"].isin(country_codes.values())]

id_frame["Party"] = id_frame["Party"].str.lower()
id_frame["Name_Short_y"] = id_frame["Name_Short_y"].str.lower()
id_frame["Name_Short_x"] = id_frame["Name_Short_x"].str.lower()
    
# replace all non-letter characters with a space
id_frame["Party"] = id_frame["Party"].apply(remove_accents)
id_frame["Name_Short_y"] = id_frame["Name_Short_y"].apply(remove_accents)
id_frame["Name_Short_x"] = id_frame["Name_Short_x"].apply(remove_accents)

# now ü → u, so the regex won't destroy it
id_frame["Party"] = id_frame["Party"].str.replace(punctuation_regex, " ", regex=True)
id_frame["Name_Short_y"] = id_frame["Name_Short_y"].str.replace(punctuation_regex, " ", regex=True)
id_frame["Name_Short_x"] = id_frame["Name_Short_x"].str.replace(punctuation_regex, " ", regex=True)

id_frame["Party"] = id_frame["Party"].str.replace(r'\s+', ' ', regex=True).str.strip()
id_frame["Name_Short_y"] = id_frame["Name_Short_y"].str.replace(r'\s+', ' ', regex=True).str.strip()
id_frame["Name_Short_x"] = id_frame["Name_Short_x"].str.replace(r'\s+', ' ', regex=True).str.strip()

In [50]:
id_frame

,Party,Name_Short_y,Name_Short_x,CountryCode,parlgov_id
0,bundnis zukunft osterreich,bzo,bzo,AUT,1536
1,freiheitliche partei osterreichs,fpo,fpo,AUT,50
2,jetzt liste pilz,pilz,pilz,AUT,2651
3,team stronach,ts,ts,AUT,2150
4,nieuw vlaamse alliantie,n va,n va,BEL,501
...,...,...,...,...,...
140,slovenska demokratska stranka,sds,sds,SVN,179
141,slovenska nacionalna stranka,sns,sns,SVN,981
142,zdruzena lista socialni demokrati,zl sd,zl,SVN,706
143,sverigedemokraterna,sd,sd,SWE,1546
144,vansterpartiet kommunisterna,v,v,SWE,882

In [57]:
id_elections = {}

for k, v in test_data.items():
    merged = v.merge(
        id_frame,
        how="left",                  
        on=["CountryCode", "Party"],
        )
    merged = merged.drop_duplicates()
    
    id_elections[k] = merged

for k, v in test_data.items():
    merged = v.merge(
        id_frame,
        how="left",                  
        left_on=["CountryCode", "Name_Short"],
        right_on=["CountryCode", "Name_Short_x"],
    )
    merged = merged.drop_duplicates()
    
    id_elections[k] = merged

In [58]:
id_elections["czechia"]

,Party_x,Name_Short,2025,CountryCode,Party_y,Name_Short_y,Name_Short_x,parlgov_id
0,ano 2011,ano,"34,5",CZE,akce nespokojenych obcanu 2011,ano,ano,2263.0
1,obcanska demokraticka strana,ods,"23,4",CZE,NaN,NaN,NaN,NaN
2,krest’anska a demokraticka unie,kdu csl,,CZE,NaN,NaN,NaN,NaN
3,top 09,top09,,CZE,NaN,NaN,NaN,NaN
4,starostove a nezavisli,stan,"11,2",CZE,NaN,NaN,NaN,NaN
5,ceska piratska strana,pirati,,CZE,NaN,NaN,NaN,NaN
6,svoboda a prima demokracie,spd,"7,8",CZE,svoboda a prima demokracie,spd,spd,2654.0
7,motoriste sobe,auto,"6,8",CZE,NaN,NaN,NaN,NaN
8,stacilo,stacilo,"4,3",CZE,NaN,NaN,NaN,NaN
9,ceska strana socialne demokraticka,cssd,STA,CZE,NaN,NaN,NaN,NaN
10,komunisticka strana cech a moravy,kscm,STA,CZE,komunisticka strana cech a moravy,kscm,kscm,1173.0
11,usvit prime demokracie,usvit,-,CZE,usvit prime demokracie,upd,usvit,2262.0

In [55]:
missing_id = []
missing_keys = []

for k, v in id_elections.items():
    missing_mask = v["parlgov_id"].isna()
    missing_id.extend(zip(v.loc[missing_mask, "Party"], v.loc[missing_mask, "CountryCode"]))
    missing_keys.extend(v.loc[missing_mask, "Party"].to_list())

missing_id

[('osterreichische volkspartei', 'AUT'),
 ('sozialdemokratische partei osterreichs', 'AUT'),
 ('das neue osterreich und liberales forum', 'AUT'),
 ('die grunen die grune alternative', 'AUT'),
 ('kommunistische partei osterreichs kpo plus', 'AUT'),
 ('team stronach fur osterreich', 'AUT'),
 ('vlaams belang', 'BEL'),
 ('mouvement reformateur', 'BEL'),
 ('parti du travail de belgique', 'BEL'),
 ('vooruit', 'BEL'),
 ('parti socialiste', 'BEL'),
 ('christen democratisch vlaams', 'BEL'),
 ('les engages', 'BEL'),
 ('open vlaamse liberalen en democraten', 'BEL'),
 ('de vlaamse groenen', 'BEL'),
 ('ecolo', 'BEL'),
 ('democrate federaliste independant', 'BEL'),
 ('lijst dedecker', 'BEL'),
 ('grazdani za evropejsko razvitie na balgaria', 'BGR'),
 ('sajuz na demokraticni sili', 'BGR'),
 ('produlzavame promjanata', 'BGR'),
 ('demokraticna balgaria', 'BGR'),
 ('vazrazdane', 'BGR'),
 ('dvizenie za prava i svobodi', 'BGR'),
 ('balgarska socialisticeska partija', 'BGR'),
 ('alians za prava i svobodi', 'BGR'),
 ('moral edinstvo cest', 'BGR'),
 ('velicie', 'BGR'),
 ('dvizenie da balgarija', 'BGR'),
 ('demokrati za silna balgarija', 'BGR'),
 ('zeleno dvizenie', 'BGR'),
 ('socijaldemokratska partija hrvatske', 'HRV'),
 ('pravo i pravda', 'HRV'),
 ('mozemo', 'HRV'),
 ('hrvatski suverenisti', 'HRV'),
 ('istarski demokratski sabor', 'HRV'),
 ('fokus', 'HRV'),
 ('umirovljenici zajedno', 'HRV'),
 ('nezavisna platforma sjever', 'HRV'),
 ('radnicka fronta', 'HRV'),
 ('hrvatski stranka prava dr ante starcevic', 'HRV'),
 ('centar', 'HRV'),
 ('hrvatska socijalno liberalna stranka', 'HRV'),
 ('hrvatska narodna stranka liberalni demokrati', 'HRV'),
 ('hrvatska demokrscanska stranka', 'HRV'),
 ('hrvatska seljacka stranka', 'HRV'),
 ('hrvatska stranka umirovljenika', 'HRV'),
 ('građansko liberalni savez', 'HRV'),
 ('dalija oreskovic i ljudi s imenom i prezimenom', 'HRV'),
 ('narodna stranka reformisti', 'HRV'),
 ('zeleno lijeva koalicija', 'HRV'),
 ('nova ljevica', 'HRV'),
 ('hrast pokret za uspjesnu hrvatsku', 'HRV'),
 ('dimokratikos synagermos', 'CYP'),
 ('dimokratiko komma', 'CYP'),
 ('kinima sosialdimokraton edek', 'CYP'),
 ('dimokratiki parataxi', 'CYP'),
 ('kinima oikologon sinergasia politon', 'CYP'),
 ('kinima allileggyi', 'CYP'),
 ('symmachia politon', 'CYP'),
 ('ano 2011', 'CZE'),
 ('obcanska demokraticka strana', 'CZE'),
 ('krest’anska a demokraticka unie', 'CZE'),
 ('top 09', 'CZE'),
 ('starostove a nezavisli', 'CZE'),
 ('ceska piratska strana', 'CZE'),
 ('motoriste sobe', 'CZE'),
 ('stacilo', 'CZE'),
 ('ceska strana socialne demokraticka', 'CZE'),
 ('socialdemokratiet i danmark', 'DNK'),
 ('venstre danmarks liberale parti', 'DNK'),
 ('liberal alliance', 'DNK'),
 ('moderaterne', 'DNK'),
 ('det konservative folkeparti', 'DNK'),
 ('danmarksdemokraterne', 'DNK'),
 ('det radikale venstre', 'DNK'),
 ('alternativet', 'DNK'),
 ('borgernes parti', 'DNK'),
 ('eesti reformierakond', 'EST'),
 ('eesti konservatiivne rahvaerakond', 'EST'),
 ('erakond eesti 200', 'EST'),
 ('sotsiaaldemokraatlik erakond', 'EST'),
 ('isamaa erakond', 'EST'),
 ('eesti vabaerakond', 'EST'),
 ('kansallinen kokoomus', 'FIN'),
 ('perussuomalaiset', 'FIN'),
 ('suomen sosialidemokraattinen puolue', 'FIN'),
 ('suomen keskusta', 'FIN'),
 ('vasemmistoliitto', 'FIN'),
 ('vihrea liitto', 'FIN'),
 ('svenska folkepartiet i finland', 'FIN'),
 ('suomen kristillisdemokraatit', 'FIN'),
 ('nouveau front populaire', 'FRA'),
 ('ensemble', 'FRA'),
 ('les republicains', 'FRA'),
 ('horizons', 'FRA'),
 ('union des democrates et independants', 'FRA'),
 ('debout la france', 'FRA'),
 ('parti socialiste', 'FRA'),
 ('parti radical de gauche', 'FRA'),
 ('les ecologistes europe ecologie les verts', 'FRA'),
 ('parti communiste francais', 'FRA'),
 ('la republique en marche', 'FRA'),
 ('mouvement democrate', 'FRA'),
 ('parti radical', 'FRA'),
 ('generations', 'FRA'),
 ('nouveau centre les centristes', 'FRA'),
 ('gauche republicaine et socialiste', 'FRA'),
 ('ensemble', 'FRA'),
 ('agir la droite constructive', 'FRA'),
 ('alliance centriste', 'FRA'),
 ('front de gauche', 'FRA'),
 ('mouvement pour la france', 'FRA'),
 ('christlich demokratische union deutschlands', 'DEU'),
 ('sozialdemokratische partei deutschlands', 'DEU'),
 ('bundnis 90 die grunen', 'DEU'),
 ('die linke', 'DEU'),
 ('christlich soziale union in bayern', 'DEU'),
 ('bundnis sahra wagenknecht', 'DEU'),
 ('freie demokratische partei', 'DEU'),
 ('sudschleswigscher wahlerverband', 'DEU'),
 ('nea dimokratia', 'GRC'),
 ('panellinio sosialistiko kinima kinima allagis', 'GRC'),
 ('spartiates', 'GRC'),
 ('dimokratiko patriotiko kinima niki', 'GRC'),
 ('plefsi eleftherias', 'GRC'),
 ('oikologoi prasinoi', 'GRC'),
 ('enosi kentroon', 'GRC'),
 ('laikos syndesmos chrysi avyi', 'GRC'),
 ('panellinio sosialistiko kinima', 'GRC'),
 ('kinima dimokraton sosialiston', 'GRC'),
 ('dimokratiki aristera', 'GRC'),
 ('christianodimokratiko komma elladas', 'GRC'),
 ('to potami', 'GRC'),
 ('anexartitoi ellinesnosi', 'GRC'),
 ('keresztenydemokrata neppart', 'HUN'),
 ('demokratikus koalicio', 'HUN'),
 ('momentum mozgalom', 'HUN'),
 ('magyar szocialista part', 'HUN'),
 ('parbeszed magyarorszagert', 'HUN'),
 ('lehet mas a politika', 'HUN'),
 ('landesselbstverwaltung der ungarndeutschen', 'HUN'),
 ('egyutt', 'HUN'),
 ('magyar liberalis part', 'HUN'),
 ('osszefogas 2014', 'HUN'),
 ('samfylkingin jafnaðarmannaflokkur islands', 'ISL'),
 ('sjalfstæðisflokkurinn', 'ISL'),
 ('viðreisn', 'ISL'),
 ('piratar', 'ISL'),
 ('vinstrihreyfingin grænt framboð', 'ISL'),
 ('bjort framtið', 'ISL'),
 ('fianna fail', 'IRL'),
 ('fine gael', 'IRL'),
 ('social democrats', 'IRL'),
 ('labour party', 'IRL'),
 ('aontu', 'IRL'),
 ('independent ireland', 'IRL'),
 ('green party', 'IRL'),
 ('people before profit', 'IRL'),
 ('solidarity', 'IRL'),
 ('100 redress', 'IRL'),
 ('independents for change', 'IRL'),
 ('partito democratico', 'ITA'),
 ('lega', 'ITA'),
 ('forza italia', 'ITA'),
 ('azione', 'ITA'),
 ('italia viva', 'ITA'),
 ('alleanza verdi e sinistra', 'ITA'),
 ('piu europa', 'ITA'),
 ('noi moderati', 'ITA'),
 ('impegno civico', 'ITA'),
 ('sudtiroler volkspartei', 'ITA'),
 ('partito comunista italiano', 'ITA'),
 ('europa verde verdi', 'ITA'),
 ('articolo uno', 'ITA'),
 ('sinistra italiana', 'ITA'),
 ('noi con italia', 'ITA'),
 ('italia al centro', 'ITA'),
 ('centro democratico', 'ITA'),
 ('unione di centro', 'ITA'),
 ('coraggio italia', 'ITA'),
 ('partito socialista italiano', 'ITA'),
 ('partito autonomista trentino tirolese', 'ITA'),
 ('sud chiama nord', 'ITA'),
 ('liberi e uguali', 'ITA'),
 ('italia europa insieme', 'ITA'),
 ('civica popolare', 'ITA'),
 ('alternativa popolare', 'ITA'),
 ('possibile', 'ITA'),
 ('area civica', 'ITA'),
 ('direzione italia', 'ITA'),
 ('scelta civica', 'ITA'),
 ('movimento per le autonomie', 'ITA'),
 ('la sinistra l arcobaleno', 'ITA'),
 ('jauna vienotiba', 'LVA'),
 ('zalo un zemnieku savieniba', 'LVA'),
 ('apvienotais saraksts', 'LVA'),
 ('nacionala apvieniba', 'LVA'),
 ('stabilitatei', 'LVA'),
 ('progresivie', 'LVA'),
 ('latvija pirmaja vieta', 'LVA'),
 ('attistibai par', 'LVA'),
 ('saskana socialdemokratiska partija', 'LVA'),
 ('konservativie', 'LVA'),
 ('apvieniba latvijai', 'LVA'),
 ('latvijas zemnieku savieniba', 'LVA'),
 ('latvijas regionu apvieniba', 'LVA'),
 ('latvijas zala partija', 'LVA'),
 ('latvijas socialdemokratiska stradnieku partija', 'LVA'),
 ('latvijai un ventspilij', 'LVA'),
 ('liepajas partija', 'LVA'),
 ('kustiba par', 'LVA'),
 ('latvijas attistibai', 'LVA'),
 ('izaugsme', 'LVA'),
 ('latvijas socialistiska partija', 'LVA'),
 ('no sirds latvijai', 'LVA'),
 ('lietuvos socialdemokratu partija', 'LTU'),
 ('tevynes sajunga lietuvos krikscionys demokratai', 'LTU'),
 ('politine partija nemuno ausra', 'LTU'),
 ('demokratu sajunga vardan lietuvos', 'LTU'),
 ('liberalu sajudis', 'LTU'),
 ('lietuvos valstieciu ir zaliuju sajunga', 'LTU'),
 ('laisves partija', 'LTU'),
 ('lietuvos lenku rinkimu akcija', 'LTU'),
 ('nacionalinis susivienijimas', 'LTU'),
 ('lietuvos regionu partija', 'LTU'),
 ('lietuvos zaliuju partija', 'LTU'),
 ('tautos ir teisingumo sajunga', 'LTU'),
 ('partija laisve ir teisingumas', 'LTU'),
 ('politine partija drasos kelias', 'LTU'),
 ('tvarka ir teisingumas', 'LTU'),
 ('lietuvos sarasas', 'LTU'),
 ('chreschtlech sozial vollekspartei', 'LUX'),
 ('letzebuergesch sozialistesch arbechterpartei', 'LUX'),
 ('demokratesch partei', 'LUX'),
 ('alternativ demokratesch reformpartei', 'LUX'),
 ('dei greng', 'LUX'),
 ('piratepartei letzebuerg', 'LUX'),
 ('democraten 66', 'NLD'),
 ('volkspartij voor vrijheid en democratie', 'NLD'),
 ('groen links', 'NLD'),
 ('partij van de arbeid', 'NLD'),
 ('christen democratisch appel', 'NLD'),
 ('ja 21', 'NLD'),
 ('boer burger beweging', 'NLD'),
 ('denk', 'NLD'),
 ('staatkundig gereformeerde partij', 'NLD'),
 ('partij voor de dieren', 'NLD'),
 ('socialistische partij', 'NLD'),
 ('christen unie', 'NLD'),
 ('50 plus', 'NLD'),
 ('volt nederland', 'NLD'),
 ('nieuw sociaal contract', 'NLD'),
 ('bij 1', 'NLD'),
 ('arbeiderpartiet', 'NOR'),
 ('høyre', 'NOR'),
 ('senterpartiet', 'NOR'),
 ('rødt', 'NOR'),
 ('miljøpartiet de grønne', 'NOR'),
 ('kristelig folkeparti', 'NOR'),
 ('venstre', 'NOR'),
 ('pasientfokus', 'NOR'),
 ('partit laburista', 'MLT'),
 ('partit nazzjonalista', 'MLT'),
 ('adpd malta s green party', 'MLT'),
 ('alternattiva demokratika', 'MLT'),
 ('partit demokratiku', 'MLT'),
 ('suwerenna polska', 'POL'),
 ('republikanie', 'POL'),
 ('koalicja obywatelska', 'POL'),
 ('platforma obywatelska', 'POL'),
 ('nowoczesna', 'POL'),
 ('inicjatywa polska', 'POL'),
 ('partia zieloni', 'POL'),
 ('trzecia droga', 'POL'),
 ('polska 2050', 'POL'),
 ('polskie stronnictwo ludowe', 'POL'),
 ('centrum dla polski', 'POL'),
 ('unia europejskich demokratow', 'POL'),
 ('nowa levica', 'POL'),
 ('levica razem', 'POL'),
 ('konfederacja wolnosc i niepodległosc', 'POL'),
 ('prawica rzeczypospolitej', 'POL'),
 ('mniejszosc niemiecka', 'POL'),
 ('wiosna', 'POL'),
 ('porozumienie jaroslawa gowina', 'POL'),
 ('twoj ruch', 'POL'),
 ('zjednoczona lewica', 'POL'),
 ('alianca democratica', 'PRT'),
 ('partido socialista', 'PRT'),
 ('iniciativa liberal', 'PRT'),
 ('livre', 'PRT'),
 ('coligacao democratica unitaria', 'PRT'),
 ('pessoas animais natureza', 'PRT'),
 ('alianca democratica', 'PRT'),
 ('juntos pelo povo', 'PRT'),
 ('partido popular monarquico', 'PRT'),
 ('partido social democrata', 'PRT'),
 ('cds partido popular', 'PRT'),
 ('partido ecologista os verdes', 'PRT'),
 ('madeira primeiro', 'PRT'),
 ('partidul social democrat', 'ROU'),
 ('partidul national liberal', 'ROU'),
 ('uniunea salvati romania', 'ROU'),
 ('s o s romania', 'ROU'),
 ('partidul oamenilor tineri', 'ROU'),
 ('uniunea democrata maghiara din romania', 'ROU'),
 ('partidul national taranesc crestin democrat', 'ROU'),
 ('alianta liberalilor si democratilor', 'ROU'),
 ('uniunea social liberala', 'ROU'),
 ('alianta romania dreapta', 'ROU'),
 ('partidul democrat liberal', 'ROU'),
 ('partidul conservator', 'ROU'),
 ('uniunea nationala pentru progresul romaniei', 'ROU'),
 ('forta civica', 'ROU'),
 ('smer slovenska socialna demokracia', 'SVK'),
 ('progresivne slovensko', 'SVK'),
 ('hlas socialna demokracia', 'SVK'),
 ('krestanskodemokraticke hnutie', 'SVK'),
 ('sloboda a solidarita', 'SVK'),
 ('republika', 'SVK'),
 ('szovetseg aliancia', 'SVK'),
 ('demokrati', 'SVK'),
 ('sme rodina', 'SVK'),
 ('kotlebovci ludova strana nase slovensko', 'SVK'),
 ('slovenska demokraticka a krestanska unia', 'SVK'),
 ('za ludi', 'SVK'),
 ('obcianska konzervativna strana', 'SVK'),
 ('strana madarskej komunity magyar kozosseg partja', 'SVK'),
 ('most hid', 'SVK'),
 ('siet', 'SVK'),
 ('gibanje svoboda', 'SVN'),
 ('nova slovenija krscanskih demokratov', 'SVN'),
 ('slovenska ljudska stranka', 'SVN'),
 ('fokus marka lotrica', 'SVN'),
 ('socialni demokrati', 'SVN'),
 ('demokrati anzeta logarja', 'SVN'),
 ('drzavljansko gibanje resnica', 'SVN'),
 ('vesna zelena stranka', 'SVN'),
 ('stranka alenke bratusek', 'SVN'),
 ('demokraticna stranka upokojencev slovenije', 'SVN'),
 ('konkretno', 'SVN'),
 ('partido popular', 'ESP'),
 ('partido socialista obrero espanol', 'ESP'),
 ('sumar', 'ESP'),
 ('esquerra republicana de catalunya', 'ESP'),
 ('junts per catalunya', 'ESP'),
 ('eusko alderdi jeltzalea', 'ESP'),
 ('coalicion canaria', 'ESP'),
 ('union del pueblo navarro', 'ESP'),
 ('teruel existe', 'ESP'),
 ('nueva canarias', 'ESP'),
 ('partit democrata europeu catala', 'ESP'),
 ('movimento sumar', 'ESP'),
 ('izquierda unida', 'ESP'),
 ('mas pais', 'ESP'),
 ('esquerra verda', 'ESP'),
 ('coalicio compromis', 'ESP'),
 ('equo', 'ESP'),
 ('ciudadanos partido de la ciudadania', 'ESP'),
 ('partido regionalista de cantabria', 'ESP'),
 ('foro asturias', 'ESP'),
 ('socialdemokratiska arbetarepartiet', 'SWE'),
 ('moderata samlingspartiet', 'SWE'),
 ('centerpartiet', 'SWE'),
 ('vansterpartiet', 'SWE'),
 ('kristdemokraterna', 'SWE'),
 ('miljopartiet de grona', 'SWE'),
 ('liberalerna', 'SWE'),
 ('schweizerische volkspartei', 'CHE'),
 ('sozialdemokratische partei der schweiz', 'CHE'),
 ('fdp die liberalen', 'CHE'),
 ('die mitte', 'CHE'),
 ('grune partei der schweiz', 'CHE'),
 ('grunliberale partei schweiz', 'CHE'),
 ('evangelische volkspartei', 'CHE'),
 ('eidgenossische demokratische union', 'CHE'),
 ('christlichdemokratische volkspartei', 'CHE'),
 ('burgerlich demokratische partei schweiz', 'CHE'),
 ('christlich soziale partei obwalden', 'CHE'),
 ('labour party', 'GBR'),
 ('conservative and unionist party', 'GBR'),
 ('reform uk', 'GBR'),
 ('liberal democrats', 'GBR'),
 ('green party', 'GBR'),
 ('scottish national party', 'GBR'),
 ('sinn fein', 'GBR'),
 ('plaid cymru', 'GBR'),
 ('alliance party of northern ireland', 'GBR'),
 ('social democratic and labour party', 'GBR'),
 ('ulster unionist party', 'GBR'),
 ('traditional unionist voice', 'GBR')]

In [ ]:
manual_id = {
'kommunistische partei osterreichs kpo plus': 996,
 'de vlaamse groenen': 528,
 'sajuz na demokraticni sili': 482,
 'produlzavame promjanata': 8994,
 'demokraticna balgaria': 9083,
 'vazrazdane': 5862,
 'alians za prava i svobodi': 'NaN',
 'moral edinstvo cest': 9812,
 'velicie': 9811,
 'dvizenie da balgarija': 2058,
 'zeleno dvizenie': 'NaN',
 'umirovljenici zajedno': 3918,
 'nezavisna platforma sjever': 'NaN',
 'hrvatski stranka prava dr ante starcevic': 3706,
 'dalija oreskovic i ljudi s imenom i prezimenom': 2524,
 'zeleno lijeva koalicija' : 'NaN', # not important
 'kinima oikologon sinergasia politon': 858,
 'krest’anska a demokraticka unie': 676,
 'motoriste sobe': 'NaN', # no ID
 'stacilo', # no ID
 'borgernes parti',
 'isamaa erakond',
 'nouveau front populaire',
 'les ecologistes europe ecologie les verts',
 'generations',
 'nouveau centre les centristes',
 'gauche republicaine et socialiste',
 'bundnis sahra wagenknecht',
 'panellinio sosialistiko kinima kinima allagis',
 'dimokratiko patriotiko kinima–niki',
 'laikos syndesmos chrysi avyi',
 'christianodimokratiko komma elladas',
 'anexartitoi ellinesnosi',
 'landesselbstverwaltung der ungarndeutschen',
 'osszefogas 2014',
 'independent ireland',
 'solidarity',
 '100 redress',
 'europa verde verdi',
 'noi con italia',
 'italia al centro',
 'sud chiama nord',
 'area civica',
 'direzione italia',
 'la sinistra l arcobaleno',
 'apvienotais saraksts',
 'apvieniba latvijai',
 'latvijai un ventspilij',
 'politine partija nemuno ausra',
 'nacionalinis susivienijimas',
 'tautos ir teisingumo sajunga',
 'partija laisve ir teisingumas',
 'politine partija drasos kelias',
 'letzebuergesch sozialistesch arbechterpartei',
 'ja 21',
 'boer burger beweging',
 '50 plus',
 'bij 1',
 'pasientfokus',
 'republikanie',
 'trzecia droga',
 'centrum dla polski',
 'nowa levica',
 'levica razem',
 'porozumienie jaroslawa gowina',
 'juntos pelo povo',
 'cds partido popular',
 'madeira primeiro',
 's o s romania',
 'partidul oamenilor tineri',
 'smer slovenska socialna demokracia',
 'szovetseg aliancia',
 'demokrati',
 'kotlebovci ludova strana nase slovensko',
 'strana madarskej komunity magyar kozosseg partja',
 'nova slovenija krscanskih demokratov',
 'fokus marka lotrica',
 'demokrati anzeta logarja',
 'drzavljansko gibanje resnica',
 'vesna–zelena stranka',
 'sumar',
 'eusko alderdi jeltzalea',
 'nueva canarias',
 'movimento sumar',
 'esquerra verda',
 'christlich soziale partei obwalden'}

In [ ]:
manual_id = {'kommunistische partei osterreichs kpo plus' : 996,
 'de vlaamse groenen' : 528,
 'produlzavame promjanata': 8994,
 'vazrazdane': 5862,
 'alians za prava i svobodi': 'NaN',
 'moral edinstvo cest': 9812,
 'velicie': 9811,